version: '3.8'
services:
  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 1s
      timeout: 1s
      retries: 30
    extra_hosts:
      - "host.docker.internal:host-gateway"
  flyway:
    image: flyway/flyway:9.11.0
    command: -url=jdbc:postgresql://host.docker.internal:${POSTGRES_PORT}/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -baselineOnMigrate=true migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
  flask:
    build: .
    env_file: .env
    environment:
      - POSTGRES_HOST=host.docker.internal
      - FLASK_RUN_PORT=${FLASK_PORT}
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    # flask requires SIGINT to stop gracefully (default stop signal from compose is SIGTERM)
    stop_signal: SIGINT
