version: "3.8"
services:
  postgres:
    image: bitnami/postgresql:15.4.0
    environment:
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
      POSTGRESQL_USERNAME: ${MASTER_USER}
      POSTGRESQL_POSTGRES_PASSWORD: ${MASTER_PASSWORD}
      POSTGRESQL_PASSWORD: ${MASTER_PASSWORD}
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: ${REPL_USER}
      POSTGRESQL_REPLICATION_PASSWORD: ${REPL_PASSWORD}
    ports:
      - "${MASTER_PORT}:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 1s
      retries: 30
    restart: unless-stopped
  flyway:
    image: flyway/flyway:9.11.0
    command: -url=jdbc:postgresql://host.docker.internal:${MASTER_PORT}/${POSTGRES_DB} -user=${MASTER_USER} -password=${MASTER_PASSWORD} -baselineOnMigrate=true migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
  flask:
    build: .
    env_file: .env
    environment:
      - MASTER_HOST=host.docker.internal
      - FLASK_RUN_PORT=${FLASK_PORT}
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    # flask requires SIGINT to stop gracefully (default stop signal from compose is SIGTERM)
    stop_signal: SIGINT
